// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3ClGLIDLgBfdiaSa6Gp01Fcaqg8X-L4Y',
    appId: '1:657616582687:web:abcb0e91829f61b1f6fd2a',
    messagingSenderId: '657616582687',
    projectId: 'oneman-project-deac6',
    authDomain: 'oneman-project-deac6.firebaseapp.com',
    storageBucket: 'oneman-project-deac6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBBWDGm6Kv8n9S7-rjKsOpStJ3L-6BPDY',
    appId: '1:657616582687:android:9b7069f76ec0c450f6fd2a',
    messagingSenderId: '657616582687',
    projectId: 'oneman-project-deac6',
    storageBucket: 'oneman-project-deac6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOfx_n3vx1ALCTgeEY372M8AqOsfLmnqY',
    appId: '1:657616582687:ios:89261e002272685cf6fd2a',
    messagingSenderId: '657616582687',
    projectId: 'oneman-project-deac6',
    storageBucket: 'oneman-project-deac6.appspot.com',
    iosBundleId: 'com.example.medapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOfx_n3vx1ALCTgeEY372M8AqOsfLmnqY',
    appId: '1:657616582687:ios:cfb1a9a2a1f21e11f6fd2a',
    messagingSenderId: '657616582687',
    projectId: 'oneman-project-deac6',
    storageBucket: 'oneman-project-deac6.appspot.com',
    iosBundleId: 'com.example.medapp.RunnerTests',
  );
}
